calculation: relax
basis_type: lcao
relax_method: cg
ecutwfc: 80
scf_thr: 1.0e-6
scf_nmax: 10 #100
relax_nmax: 2
force_thr_ev: 0.05
stress_thr: 1.0
ks_solver: genelpa
smearing_method: gaussian
smearing_sigma: 0.02
mixing_type: broyden
mixing_beta: 0.4
nspin: 2
symmetry: 1
out_chg: 0


