calculation: cell-relax
basis_type: lcao
ecutwfc: 100
scf_thr: 1.0e-8
scf_nmax: 10 #100
relax_nmax: 10 #100
force_thr_ev: 0.01
stress_thr: 0.5
relax_method: bfgs #cg
ks_solver: genelpa
smearing_method: gaussian
smearing_sigma: 0.02
mixing_type: broyden
mixing_beta: 0.4
nspin: 2
symmetry: 1
out_chg: 0
