calculation: cell-relax
basis_type: lcao
ecutwfc: 120
scf_thr: 1.0e-6
scf_nmax: 100 #100
relax_nmax: 100 #100
force_thr_ev: 0.01
stress_thr: 0.5
relax_method: cg
ks_solver: genelpa
smearing_method: gaussian
smearing_sigma: 0.02
mixing_type: broyden
mixing_beta: 0.4
nspin: 2
symmetry: 1
out_chg: 0
cal_force: 1
cal_stress: 1
out_level: i
out_stru: 1
