calculation: scf
basis_type: lcao
ecutwfc: 100
scf_thr: 1.0e-7
scf_nmax: 100
ks_solver: genelpa
smearing_method: gaussian
smearing_sigma: 0.02
mixing_type: broyden
mixing_beta: 0.4
nspin: 2
symmetry: 1
out_chg: 1
